INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','100',N'系統資訊','AdminHomePage.aspx','0',N'系統資訊','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','101',N'系統資訊管理','SystemProfile.aspx','100',N'系統資訊','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','102',N'使用者管理','AdminUserList.aspx','100',N'系統資訊','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','103',N'權限群組管理','RuleGroupList.aspx','100',N'系統資訊','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','104',N'異常管理者資訊','ADUserList.aspx','100',N'系統資訊','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','105',N'人員異動處理','UserChangeList.aspx','100',N'系統資訊','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','106',N'AD_SERVER管理','ADServerList.aspx','100',N'系統資訊','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','107',N'IP使用者管理','UserList.aspx','100',N'系統資訊','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','200',N'資源管理','AdminHomePage.aspx','0',N'資源管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','201',N'營設管理','FacilitiesList.aspx','200',N'營區資源管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','202',N'單位資料管理與AD同步作業','UnitIndex.aspx','200',N'營區資源管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','203',N'IP/網段資源管理','NetscopeList.aspx','200',N'營區資源管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','204',N'Switch資源管理','SwitchDeviceList.aspx','200',N'營區資源管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','205',N'DHCP Server管理','DHCPServerList.aspx','200',N'營區資源管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','206',N'DHCP資源管理','AdminHomePage.aspx','200',N'營區資源管理','0','0','0','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','207',N'管理資訊同步','MgrDataSynchronous.aspx','200',N'營區資源管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','208',N'網路指令參數管理','NetCommandModelList.aspx','200',N'營區資源管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','209',N'路由器管理','RouterList.aspx','200',N'營區資源管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','210',N'網路設備指令管理','NetDeviceModelList.aspx','200',N'營區資源管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','300',N'網路資訊管理','AdminHomePage.aspx','0',N'網路資訊管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','301',N'IP註冊管理','IPConfigList.aspx','300',N'網路資訊管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','302',N'IP使用現況','IPUserList.aspx','300',N'網路資訊管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','303',N'IP使用歷史紀錄','UserIPList.aspx','300',N'網路資訊管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','304',N'人員註冊紀錄','UserIPRecordList.aspx','300',N'網路資訊管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','306',N'Switch即時監控','MonitSwitchList.aspx','300',N'網路資訊管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','400',N'網路管理統計','AdminHomePage.aspx','0',N'網路管理統計','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','401',N'Scope 使用統計','ScopeList.aspx','400',N'網路管理統計','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','402',N'使用者管理紀錄','MgrRecordList.aspx','400',N'網路管理統計','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','403',N'排程程式執行紀錄','ScheduleList.aspx','400',N'網路管理統計','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','404',N'查詢管理/操作/設定紀錄','MgrRecordSetList.aspx','400',N'網路管理統計','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','405',N'線上管理','OnLineMgrList.aspx','400',N'網路管理統計','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','406',N'單位網站管理紀錄','AdminHomePage.aspx','400',N'網路管理統計','0','0','0','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','407',N'Switch Port違規歷史紀錄','SwitchMonitorLog.aspx','400',N'網路管理統計','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','500',N'監控及繞道','AdminHomePage.aspx','0',N'監控及繞道','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','501',N'即時監控參數管理','MonitComList.aspx','500',N'即時監控','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','502',N'系統效能監控','MoniSysPerformanceList.aspx','500',N'即時監控','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','600',N'下載專區','AdminHomePage.aspx','0',N'相關文件下載管理','0','0','0','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','601',N'相關文件下載管理','PageDownload.aspx','600',N'相關文件下載管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','602',N'修正檔下載管理','PatchDownload.aspx','600',N'相關文件下載管理','0','0','1','A')
INSERT INTO  [dbo].[admin_tools] ([at_spid],[at_id],[at_name] ,[at_url],[at_class],[at_class_name],[at_mflag],[at_openflag],[AT_STATUS],[AT_GROUP]) 
VALUES ('0','603',N'其他下載管理','OtherDownload.aspx','600',N'相關文件下載管理','0','0','1','A')
